/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CeoStudentsNewRouteImport } from './routes/ceo/students-new'
import { Route as CeoAllStudentsRouteImport } from './routes/ceo/all-students'
import { Route as CeoAllProgramsRouteImport } from './routes/ceo/all-programs'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoStudentsNewRoute = CeoStudentsNewRouteImport.update({
  id: '/ceo/students-new',
  path: '/ceo/students-new',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoAllStudentsRoute = CeoAllStudentsRouteImport.update({
  id: '/ceo/all-students',
  path: '/ceo/all-students',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoAllProgramsRoute = CeoAllProgramsRouteImport.update({
  id: '/ceo/all-programs',
  path: '/ceo/all-programs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/ceo/all-programs': typeof CeoAllProgramsRoute
  '/ceo/all-students': typeof CeoAllStudentsRoute
  '/ceo/students-new': typeof CeoStudentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/ceo/all-programs': typeof CeoAllProgramsRoute
  '/ceo/all-students': typeof CeoAllStudentsRoute
  '/ceo/students-new': typeof CeoStudentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/ceo/all-programs': typeof CeoAllProgramsRoute
  '/ceo/all-students': typeof CeoAllStudentsRoute
  '/ceo/students-new': typeof CeoStudentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/ceo/all-programs'
    | '/ceo/all-students'
    | '/ceo/students-new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/ceo/all-programs'
    | '/ceo/all-students'
    | '/ceo/students-new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/ceo/all-programs'
    | '/ceo/all-students'
    | '/ceo/students-new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  CeoAllProgramsRoute: typeof CeoAllProgramsRoute
  CeoAllStudentsRoute: typeof CeoAllStudentsRoute
  CeoStudentsNewRoute: typeof CeoStudentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo/students-new': {
      id: '/ceo/students-new'
      path: '/ceo/students-new'
      fullPath: '/ceo/students-new'
      preLoaderRoute: typeof CeoStudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo/all-students': {
      id: '/ceo/all-students'
      path: '/ceo/all-students'
      fullPath: '/ceo/all-students'
      preLoaderRoute: typeof CeoAllStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo/all-programs': {
      id: '/ceo/all-programs'
      path: '/ceo/all-programs'
      fullPath: '/ceo/all-programs'
      preLoaderRoute: typeof CeoAllProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  CeoAllProgramsRoute: CeoAllProgramsRoute,
  CeoAllStudentsRoute: CeoAllStudentsRoute,
  CeoStudentsNewRoute: CeoStudentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
